# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-24 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mechanics',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
    ]
