# Generated by Django 2.0.2 on 2018-03-08 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanics',
            name='service_name',
        ),
    ]
