# Generated by Django 2.0.2 on 2018-03-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterGarage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garage_name', models.CharField(max_length=45)),
                ('garage_location', models.CharField(max_length=50)),
                ('garage_email', models.EmailField(max_length=254)),
                ('garage_telephone', models.IntegerField()),
            ],
        ),
    ]
